# Generated by Django 5.1.3 on 2024-11-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_clients_employees_productcategories_products_roles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'managed': False, 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'managed': False, 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='productcategories',
            options={'managed': False, 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False, 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': False, 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'managed': False, 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'managed': False, 'verbose_name_plural': 'Транзакции'},
        ),
    ]
